### ISSUE TITLE
Auto link table links

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_tabledisplay#31]
links don't work
![image](https://user-images.githubusercontent.com/17744188/91294885-dc011c80-e7a2-11ea-9dae-26f405e12b09.png)

**Comment by piorek** [comment]
@EfimovVladimir i will check this but there was an issue filled some time ago that this is a security issue and currently links are not clickable by default. It can be changed via configuration

https://github.com/twosigma/beakerx_tabledisplay/blob/master/beakerx_tabledisplay/beakerx_tabledisplay/tabledisplay.py#L510-L520

**Comment by ildipo** [comment]
Closing this since behavior is as expected
